name: Daily Deployment

on:
  schedule:
    # Runs at 05:00 UTC (1:00 AM EST, 6:00 AM GMT, 7:00 AM CET)
    - cron: '0 5 * * *'

  # Optional: Allow manual triggers from GitHub UI
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger deployment
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          # Create and push an empty commit to trigger deployment
          git commit --allow-empty -m "chore: daily deployment trigger"
          git push origin main
